backend/accounts/urls.py
from django.urls import path
from .views import *
from . import views

app_name = 'accounts'

urlpatterns = [
    path('home/', HomePageView.as_view(), name='home'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('login/', Login.as_view(), name='login'),
    path('logout/', Logout.as_view(), name='logout'),
    path('done/', Done.as_view(), name='done'),
    path('send_otp/', SendOtp.as_view(), name='send_otp'),
    path('otp_check/', Check.as_view(), name='otp_check'),
    path('', views.index, name='index'),
    path('archive/<int:pk>', views.archive_note_view, name = 'archive'),
    path('archives/', views.archive_page_view, name = 'archive_page'),
    path('unarchive/<int:pk>', views.unarchive_note_view, name = 'unarchive'),
    path('trash/<int:pk>', views.trash_note, name = 'trash'),
    path('trash/', views.trash_page_view, name='trash_page'),
    path('trash/<int:pk>', views.delete_note_permanently, name = 'delete'),
    path('login/', views.login , name='login'),
    path('save/', views.save_note , name='save'),
    path('search/', views.search_function, name='search'),
    # path('change_password/', Password_reset.as_view(), name='change_password'),
]

backend/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
]

backend/accounts/models.py
from django.db import models

from django.utils import timezone

# Create your models here.

class Note(models.Model):
    title = models.CharField(max_length=100)
    body = models.TextField(max_length=15)
    archive = models.BooleanField(default=False)
    trash = models.BooleanField(default=False)
    pin = models.BooleanField(default=False)
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.title}'

backend/accounts/forms.py
from django.contrib.auth.models import User
from django import forms
from . models import Note

class AddNote(forms.ModelForm):
    title = forms.CharField(required=True, widget=forms.widgets.TextInput(attrs={"placeholder":"Title", "class":"form-control"}), label="")
    body = forms.CharField(required=True, widget=forms.widgets.TextInput(attrs={"placeholder":"Enter Notes...", "class":"form-control"}), label="")
    class Meta:
        model = Note
        exclude = ('user', 'archive', 'trash', 'pin', 'created_at', 'updated_at')

backend/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from .utility import generate_otp
from django.core.mail import send_mail
from django.core.cache import cache
from .models import Note
from . forms import AddNote
from django.db.models import Q






# Create your views here.
class HomePageView(View):
    template_name = 'home.html'

    def get(self, request):

        return render(request, self.template_name)
    
class SignUpView(View):
    template_name = 'signup.html'

    def get(self, request):
        return render(request, self.template_name)
    
    def post(self, request):
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        confirm_password = request.POST['confirm_password']
       
        if password != confirm_password:
            return redirect('accounts:signup')
        else:
            request.session['username'] = username #this place might not be needed
            user = User.objects.create_user(username=username, password=password, email=email)
            user.save()
            return redirect('accounts:login')

class Login(View):
    template_name = 'login.html'

    def get(self, request):
        return render(request, self.template_name)
    
    def post(self, request):
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            messages.success(request, f"Welcome {username}, enter your notes")
            return redirect('accounts:index')
        else:
            return redirect('accounts:login')
        
class Logout(View):

    def get(self, request):
        logout(request)
        return redirect('accounts:index')

class SendOtp(View):
    template_name = 'send_otp.html'

    def get(self, request):
        otp = generate_otp()
        request.session['otp'] = otp
        context = {
            'otp': otp
        }
        return render(request, self.template_name, context)
    
    def post(self, request):
        email_address = request.POST['email_address']
        request.session['email_address'] = email_address
        user = User.objects.get(email=email_address)

        cache.set(f'otp_{email_address}', request.session['otp'], 300)

        body = f'the otp >> {request.session['otp']} and incase you forgot, your username is {user.username}'
        send_mail(
            'Password reset',
            body,
            from_email='preciousakpe266@gmail.com',
            recipient_list=[email_address]
        )

        return redirect('accounts:otp_check')
    
class Done(View):
    template_name = 'done_send.html'

    def get(self, request):
        return render(request, self.template_name)
    
class Check(View):
    template_name = 'check.html'

    def get(self, request):
        return render(request, self.template_name)
    
    def post(self, request):
        email = request.POST['email']
        otp_checker = request.POST['otp_checker']

        cached_otp = cache.get(f'otp_{email}')
        
        if cached_otp and otp_checker == cached_otp:
            # valid otp
            return redirect('accounts:done')
        else:
            return redirect('accounts:otp_check')
        


def search_function(request):
    q = request.GET.get('q', '')  # Get 'q' from request.GET, default to an empty string if not present
    if q != '':
        multiple_q = Q(Q(title__icontains=q) | Q(body__icontains=q))
        notes = Note.objects.filter(multiple_q)
        messages.success(request, 'Here\'s what I found')
    else:
        messages.error(request, 'Sorry, Note Not Found!')
        notes = Note.objects.filter(archive=False, trash=False)
    return render(request, 'search_results.html', {'notes': notes, 'query': q})


def index(request):
   
    notes = Note.objects.filter(archive=False, trash=False)
    form = AddNote(request.POST or None)
    return render(request, 'index.html', {'notes': notes, 'form': form})


def save_note(request):
    form = AddNote(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
                form.save()
                return redirect('accounts:index')
    
    else:
        messages.error(request, 'You must be logged in to add a record')
        return redirect('accounts:index')
    # return render(request, 'index.html', {'form': form})



# Archive a specific note
def archive_note_view(request, pk):
    notes = get_object_or_404(Note, id=pk)
    notes.archive = True
    notes.save()
    messages.success(request, 'note archived')
    return redirect('accounts:archive_page')

#displaying the archive page
def archive_page_view(request):
    archived_notes = Note.objects.filter(archive=True, trash=False)
    
    return render(request, 'archive.html', {'notes': archived_notes})

#unarchive fuctionality   
def unarchive_note_view(request, pk):
    note = get_object_or_404(Note, id=pk)
    note.archive = False
    note.save()
    messages.success(request, 'note unarchived')
    return redirect('accounts:index')  # Redirect to the archive page

#trash fuctionality   
def trash_note(request, pk):
    note = Note.objects.get(id=pk)
    note.trash = True
    note.save()
    messages.success(request, 'note sent to trash')
    return redirect('accounts:trash_page') 

#trash page view
def trash_page_view(request):
    trash_note = Note.objects.filter(trash=True, archive=False)
    return render(request, 'trash.html', {'notes':trash_note})


def delete_note_permanently(request, pk):
    if request.method == 'POST':
        delete_it = Note.objects.get(id=pk)
        delete_it.delete()
        return redirect('accounts:index')

backend/templates/done_send.html
{% extends 'base.html' %}

{% block content %}

<h1>Email sent successfully</h1>

{% endblock content %}

backend/templates/home.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<!-- <p><a href="{% url 'accounts:logout' %}"><button>Logout</button></a> </p> -->

{% if user.is_authenticated %}
    <!-- <p>Welcome {{user.username}}, your email {{user.email}}</p>
    <p>Welcome {{username}}</p> 

    <h1>Write your notes here</h1>
    <br><br> -->

    <!DOCTYPE html>
    <html lang="en">

    <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
    <title>No+e</title>
    </head>

    <body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
            <a class="navbar-brand" href="{% url 'accounts:home' %}">
            <img src="{% static 'images/note_logo.svg.png' %}" alt="" width="118px" height="26.49px">
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <form class="d-flex w-50 ms-5">
                <input class="form-control me-3 w-100 search-bar" type="search" placeholder="Type to Search"
                aria-label="Search">
            </form>
            <div>
                <a href="archive.html" class="text-decoration-none"><svg xmlns="http://www.w3.org/2000/svg" width="24"
                    height="24" fill="white" viewBox="0 0 24 24">
                    <path
                    d="M20.54 5.23l-1.39-1.68C18.88 3.21 18.47 3 18 3H6c-.47 0-.88.21-1.16.55L3.46 5.23C3.17 5.57 3 6.02 3 6.5V19c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2V6.5c0-.48-.17-.93-.46-1.27zM6.24 5h11.52l.83 1H5.42l.82-1zM5 19V8h14v11H5zm11-5.5l-4 4-4-4 1.41-1.41L11 13.67V10h2v3.67l1.59-1.59L16 13.5z">
                    </path>
                </svg>
                </a>
                <a href="trash.html">
                <img src="./images/ic_outline-delete.png" alt="">
                </a>
            </div>
            </div>
        </div>
        </nav>
    </header>

    <section class="py-4">
        <div class="container col-7 form-section">
        
        <div class=" col-12 border border-bottom-0">
            <form class="w-100">

            <input class="form-control title-bar" type="text" placeholder="Title" aria-label="Search">

            <input class="form-control title-bar" type="text" placeholder="Take  a note..." aria-label="Search">

            </form>
        </div>


        <div class="d-flex gap-4 ps-2 border border-top-0">
            <a href="#">
            <img src="./images/ant-design_edit-twotone.png" alt="" width="24px" height="24px">
            </a>
            <a href="#">
            <svg xmlns="http://www.w3.org/2000/svg" width="24"
            height="24" fill="white" viewBox="0 0 24 24">
            <path
                d="M20.54 5.23l-1.39-1.68C18.88 3.21 18.47 3 18 3H6c-.47 0-.88.21-1.16.55L3.46 5.23C3.17 5.57 3 6.02 3 6.5V19c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2V6.5c0-.48-.17-.93-.46-1.27zM6.24 5h11.52l.83 1H5.42l.82-1zM5 19V8h14v11H5zm11-5.5l-4 4-4-4 1.41-1.41L11 13.67V10h2v3.67l1.59-1.59L16 13.5z">
            </path>
            </svg>
            </a>
            <a href="">
            <img src="./images/ic_outline-delete.png" alt="">
            </a>
        </div>

        </div>
    </section>


    <section class="pt-3">
        <div class="container col-7 d-flex flex-wrap gap-3">
        <div class="card border-secondary mb-3" style="width: 243px; height: 137px;">
            <div class="card-body text-primary">
            <p class="card-text">Design the landing page</p>
            </div>
            <div class="d-flex gap-1 justify-content-end">
            <a href="#">
                <img src="./images/ant-design_edit-twotone.png" alt="" width="24px" height="24px">
            </a>
            <a href="#">
                <svg xmlns="http://www.w3.org/2000/svg" width="24"
                height="24" fill="white" viewBox="0 0 24 24">
                <path
                d="M20.54 5.23l-1.39-1.68C18.88 3.21 18.47 3 18 3H6c-.47 0-.88.21-1.16.55L3.46 5.23C3.17 5.57 3 6.02 3 6.5V19c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2V6.5c0-.48-.17-.93-.46-1.27zM6.24 5h11.52l.83 1H5.42l.82-1zM5 19V8h14v11H5zm11-5.5l-4 4-4-4 1.41-1.41L11 13.67V10h2v3.67l1.59-1.59L16 13.5z">
                </path>
            </svg>
            </a>
            <a href="">
                <img src="./images/ic_outline-delete.png" alt="">
            </a>
            </div>
        </div>
        <div class="card border-secondary mb-3" style="width: 243px; height: 137px;">
            <div class="card-body text-primary">
            <p class="card-text">Design the landing page</p>
            </div>
            <div class="d-flex gap-1 justify-content-end">
            <a href="#">
                <img src="./images/ant-design_edit-twotone.png" alt="" width="24px" height="24px">
            </a>
            <a href="#">
                <svg xmlns="http://www.w3.org/2000/svg" width="24"
                height="24" fill="white" viewBox="0 0 24 24">
                <path
                d="M20.54 5.23l-1.39-1.68C18.88 3.21 18.47 3 18 3H6c-.47 0-.88.21-1.16.55L3.46 5.23C3.17 5.57 3 6.02 3 6.5V19c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2V6.5c0-.48-.17-.93-.46-1.27zM6.24 5h11.52l.83 1H5.42l.82-1zM5 19V8h14v11H5zm11-5.5l-4 4-4-4 1.41-1.41L11 13.67V10h2v3.67l1.59-1.59L16 13.5z">
                </path>
            </svg>
            </a>
            <a href="">
                <img src="./images/ic_outline-delete.png" alt="">
            </a>
            </div>
        </div>
        <div class="card border-secondary mb-3" style="width: 243px; height: 137px;">
            <div class="card-body text-primary">
            <p class="card-text">Design the landing page</p>
            </div>
            <div class="d-flex gap-1 justify-content-end">
            <a href="#">
                <img src="./images/ant-design_edit-twotone.png" alt="" width="24px" height="24px">
            </a>
            <a href="#">
                <svg xmlns="http://www.w3.org/2000/svg" width="24"
                    height="24" fill="white" viewBox="0 0 24 24">
                    <path
                    d="M20.54 5.23l-1.39-1.68C18.88 3.21 18.47 3 18 3H6c-.47 0-.88.21-1.16.55L3.46 5.23C3.17 5.57 3 6.02 3 6.5V19c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2V6.5c0-.48-.17-.93-.46-1.27zM6.24 5h11.52l.83 1H5.42l.82-1zM5 19V8h14v11H5zm11-5.5l-4 4-4-4 1.41-1.41L11 13.67V10h2v3.67l1.59-1.59L16 13.5z">
                    </path>
                </svg>
            </a>
            <a href="">
                <img src="./images/ic_outline-delete.png" alt="">
            </a>
            </div>
        </div>
        <div class="card border-secondary mb-3" style="width: 243px; height: 137px;">
            <div class="card-body text-primary">
            <p class="card-text">Design the landing page</p>
            </div>
            <div class="d-flex gap-1 justify-content-end">
            <a href="#">
                <img src="./images/ant-design_edit-twotone.png" alt="" width="24px" height="24px">
            </a>
            <a href="#">
                <svg xmlns="http://www.w3.org/2000/svg" width="24"
                    height="24" fill="white" viewBox="0 0 24 24">
                    <path
                    d="M20.54 5.23l-1.39-1.68C18.88 3.21 18.47 3 18 3H6c-.47 0-.88.21-1.16.55L3.46 5.23C3.17 5.57 3 6.02 3 6.5V19c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2V6.5c0-.48-.17-.93-.46-1.27zM6.24 5h11.52l.83 1H5.42l.82-1zM5 19V8h14v11H5zm11-5.5l-4 4-4-4 1.41-1.41L11 13.67V10h2v3.67l1.59-1.59L16 13.5z">
                    </path>
                </svg>
            </a>
            <a href="">
                <img src="./images/ic_outline-delete.png" alt="">
            </a>
            </div>
        </div>
        <div class="card border-secondary mb-3" style="width: 243px; height: 137px;">
            <div class="card-body text-primary">
            <p class="card-text">Design the landing page</p>
            </div>
            <div class="d-flex gap-1 justify-content-end">
            <a href="#">
                <img src="./images/ant-design_edit-twotone.png" alt="" width="24px" height="24px">
            </a>
            <a href="#">
                <svg xmlns="http://www.w3.org/2000/svg" width="24"
                height="24" fill="white" viewBox="0 0 24 24">
                <path
                d="M20.54 5.23l-1.39-1.68C18.88 3.21 18.47 3 18 3H6c-.47 0-.88.21-1.16.55L3.46 5.23C3.17 5.57 3 6.02 3 6.5V19c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2V6.5c0-.48-.17-.93-.46-1.27zM6.24 5h11.52l.83 1H5.42l.82-1zM5 19V8h14v11H5zm11-5.5l-4 4-4-4 1.41-1.41L11 13.67V10h2v3.67l1.59-1.59L16 13.5z">
                </path>
            </svg>
            </a>
            <a href="">
                <img src="./images/ic_outline-delete.png" alt="">
            </a>
            </div>
        </div>
        <div class="card border-secondary mb-3" style="width: 243px; height: 137px;">
            <div class="card-body text-primary">
            <p class="card-text">Design the landing page</p>
            </div>
            <div class="d-flex gap-1 justify-content-end">
            <a href="#">
                <img src="./images/ant-design_edit-twotone.png" alt="" width="24px" height="24px">
            </a>
            <a href="#">
                <svg xmlns="http://www.w3.org/2000/svg" width="24"
                    height="24" fill="white" viewBox="0 0 24 24">
                    <path
                    d="M20.54 5.23l-1.39-1.68C18.88 3.21 18.47 3 18 3H6c-.47 0-.88.21-1.16.55L3.46 5.23C3.17 5.57 3 6.02 3 6.5V19c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2V6.5c0-.48-.17-.93-.46-1.27zM6.24 5h11.52l.83 1H5.42l.82-1zM5 19V8h14v11H5zm11-5.5l-4 4-4-4 1.41-1.41L11 13.67V10h2v3.67l1.59-1.59L16 13.5z">
                    </path>
                </svg>
            </a>
            <a href="">
                <img src="./images/ic_outline-delete.png" alt="">
            </a>
            </div>
        </div>
        </div>
    </section>







    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>

    </body>

    </html>

{% else %}
<p>You're not logged in.</p>
<a href="{% url 'accounts:login' %}">Log In</a> |
<a href="{% url 'accounts:signup' %}">Sign Up</a>

{% endif %}

{% endblock content %}

backend/templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
  <link rel="stylesheet" href="{% static 'css/home.css' %}">
  <title>index</title>
</head>

<body>
  <header>
    <div class="container">
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
      {{ message }}
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
    {% endif %}
    <nav class="navbar navbar-expand-lg navbar-light">
        <a class="navbar-brand" href="{% url 'accounts:index' %}">
          <img src="{% static 'images/note_logo.svg.png' %}" alt="" width="118px" height="26.49px">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          
          <!-- searchbar function -->
          <form class="d-flex w-50 ms-5" role="search" method="GET" action="{% url 'accounts:search' %}">
            <input class="form-control me-3 w-100 search-bar" name="q" type="search" placeholder="Search" value="{{ request.GET.q }}" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>






          <div>
            <a href="{% url 'accounts:archive_page' %}" class="text-decoration-none"><svg xmlns="http://www.w3.org/2000/svg" width="24"
                height="24" fill="white" viewBox="0 0 24 24">
                <path
                  d="M20.54 5.23l-1.39-1.68C18.88 3.21 18.47 3 18 3H6c-.47 0-.88.21-1.16.55L3.46 5.23C3.17 5.57 3 6.02 3 6.5V19c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2V6.5c0-.48-.17-.93-.46-1.27zM6.24 5h11.52l.83 1H5.42l.82-1zM5 19V8h14v11H5zm11-5.5l-4 4-4-4 1.41-1.41L11 13.67V10h2v3.67l1.59-1.59L16 13.5z">
                </path>
              </svg>
            </a>
            <a href="{% url 'accounts:trash_page' %}">
              <img src="{% static 'images/ic_outline-delete.png' %}" alt="">
            </a>
          </div>
        </div>
      </div>
    </nav>
  </header>

  <section class="py-4">
    <div class="container col-7 form-section">
      
      <div class=" col-12">
        
        <form class="w-100" method="post" action="{% url 'accounts:save' %}">
          {% csrf_token %}

          {{ form.as_p }}

          <!-- <input class="form-control title-bar" type="text" placeholder="Title" aria-label="Search">

          <input class="form-control title-bar" type="text" placeholder="Take  a note..." aria-label="Search"> -->
        <button type="submit" class="btn btn-secondary" action="{% url 'accounts:index' %}">Save</button>

        </form>
      </div>   
      
      <br/>
      

    </div>
  </section>

<!-- note taking functionality -->
  <section class="pt-3">
    <div class="container col-7 d-flex flex-wrap gap-3">
      
    {% if notes %}
        {% for note in notes %}
      
      <div class="card border-secondary mb-3" style="width: 243px; height: 150px;">
        <div class="card-body text-primary">
          <p class="card-text">{{ note.title }}</p>
          <p class="card-text">{{ note.body }}</p>
          
        </div>
        
        <div class="d-flex gap-1 justify-content-end">
          
          <a href="{% url 'accounts:archive' note.id %}">
            <svg xmlns="http://www.w3.org/2000/svg" width="24"
            height="24" fill="white" viewBox="0 0 24 24">
            <path
              d="M20.54 5.23l-1.39-1.68C18.88 3.21 18.47 3 18 3H6c-.47 0-.88.21-1.16.55L3.46 5.23C3.17 5.57 3 6.02 3 6.5V19c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2V6.5c0-.48-.17-.93-.46-1.27zM6.24 5h11.52l.83 1H5.42l.82-1zM5 19V8h14v11H5zm11-5.5l-4 4-4-4 1.41-1.41L11 13.67V10h2v3.67l1.59-1.59L16 13.5z">
            </path>
          </svg>
          </a>

          
            <a href="{% url 'accounts:trash' note.id %}">
            <img src="{% static 'images/ic_outline-delete.png' %}" alt="Send to Trash"></a>

      
        
          <!-- <a href="{% url 'accounts:delete' note.id %}">
            <img src="{% static 'images/ic_outline-delete.png' %}" alt="">
          </a> -->
        </div>
      </div>
      {% endfor %}
      {% endif %} 
    
    </div>
  </section>







  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
    crossorigin="anonymous"></script>

</body>

</html>

backend/templates/login.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<!-- <form action="" method="post">

    {% csrf_token %}

    <label for="username">Username: </label>
    <input type="text" name="username" placeholder="Username">

    <br><br>

    <label for="password">Password: </label>
    <input type="password" name="password" placeholder="Password">

    <br><br>

    <button type="submit">Login</button>

</form>

<a href="{% url 'accounts:send_otp' %}"><button>Reset password</button></a> -->

<section class="Note-hero bg-dark">

<div class="container">
    
    <div class="row p-5">
        <div class="logo-holder text-center col-xl-12 col-md-12">

            <!-- <img class="logo " src="./images/no+e-removebg-preview.png" alt="note-logo" min-width="550px" height="95px"> -->
            <img class="logo " src="{% static 'images/no+e-removebg-preview.png' %}" alt="note-logo" min-width="550px" height="95px">
            </div>

            <div class="container mt-5 p-5">

            <h1 class="display-5 fw-bold text-center">Log In</h1>
    
            <form action="" method="post">
                {% csrf_token %}
                <div class="mb-3">
                <label for="name" class="form-label">Name</label>
                <input type="text" class="form-control" id="name" name="username" placeholder="Enter your name" required>
                </div>
                
                <div class="mb-3">
                <label for="password" class="form-label">Password</label>
                <input type="password" class="form-control" id="password" name="password" placeholder="Enter your password" required>
                </div>
                
                <div class="submit-holder text-center pt-4">
                <button type="submit" class="btn btn-primary ps-5 pe-5 ">Submit</button>
                </div>
            </form>
            </div>
        
        </div>
    
        </div>
    </div>

</div>

</section>


    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
    crossorigin="anonymous"></script>

{% endblock content %}